name: Release TGZ

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v0.3.5). Leave empty to use package.json version"
        type: string
        required: false
        default: ""
      prerelease:
        description: "Mark as prerelease"
        type: boolean
        required: false
        default: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies (no lifecycle scripts)
        run: yarn install --frozen-lockfile --ignore-scripts --non-interactive

      - name: Build
        run: yarn build

      - name: Read version from package.json
        id: pkg
        run: |
          node -e "const p=require('./package.json'); console.log('VERSION='+p.version); console.log('NAME='+p.name);" >> "$GITHUB_OUTPUT"

      - name: Compute tag
        id: tag
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            echo "TAG=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=v${{ steps.pkg.outputs.VERSION }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate package tgz
        id: pack
        run: |
          npm pack --silent
          echo "TARBALL=${{ steps.pkg.outputs.NAME }}-${{ steps.pkg.outputs.VERSION }}.tgz" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: ${{ steps.tag.outputs.TAG }}
          files: ${{ steps.pack.outputs.TARBALL }}
          draft: false
          prerelease: ${{ inputs.prerelease }}

